CREATE TABLE IF NOT EXISTS "csv_metadata" (
  "id" SERIAL PRIMARY KEY,
  "table_name" TEXT NOT NULL UNIQUE,
  "file_name" TEXT NOT NULL,
  "column_names" JSONB NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
); 