version: '3.8'

services:
  server:
    image: honeyjar-server:latest
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:Password1@db:5432/client_db
      - PG_USER=postgres
      - PG_PASSWORD=Password1
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=client_db
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - TZ=UTC
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run db:generate && npx drizzle-kit push:pg --force && npm run db:migrate && npm start"

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1
      - POSTGRES_DB=client_db
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 